name: Build

on: [push]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build
        run: |
          cargo build --release
          cp target/release/derpc .

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: derpc-linux
          path: |
            derpc
            config.example.toml

  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build
        run: |
          cargo build --release
          cp target/release/derpc .

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: derpc-macos
          path: |
            derpc
            config.example.toml

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build
        run: |
          cargo build --release
          cp target/release/derpc.exe .

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: derpc-windows
          path: |
            derpc.exe
            config.example.toml
